source 'https://github.com/CocoaPods/Specs.git'

target 'AZWheelPickerView', :exclusive => true do
  pod "AZWheelPickerView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AZWheelPickerView", :path => "../"

  pod 'FBSnapshotTestCase'
end
